### ISSUE TITLE
Store Figurant jID as Meta/Add Select in Persona Generator

### ISSUE THREAD

**Issue by SulpherStaer** [eosfrontier/FigurantManagement#4]
We need to send meta data after the character is created.

- Figurant jID

We also need to display this data in the figurant overview

- [x] Josh will send this data from POST/PUT endpoints
- [ ] Josh will add a meta field in the POST that allows Silvester to store the Joomla ID of the figurant who is playing the persona so that we can later retrieve PasFotos and OC Naams and such.
- [ ] Silvester will add a dropdown in the Persona Generator to allow Figuhuis to choose OC name of the Figurant

**Comment by SulpherStaer** [comment]
Past me was not clear. Why is this needed again?... Think hard future me. Think hard. Did it have something to do with pictures?...

**Comment by SulpherStaer** [comment]
I do not remember why this was required at all. It is labeled should, Why?

**Comment by SulpherStaer** [comment]
https://github.com/eosfrontier/PersonaGenerator/issues/18

**Comment by WafflesMcDuff** [comment]
This has now been accomplished by adding a column in ecc_characters
